# Generated by Django 3.0.4 on 2020-03-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200322_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='test',
        ),
        migrations.AddField(
            model_name='patient',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
