# Generated by Django 3.0.4 on 2020-03-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20200322_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
